package net.ib.ixpert.ops.wuwagent.agent.stage0

import com.google.gson.GsonBuilder
import net.ib.ixpert.ops.wuwagent.client.LLMClient
import net.ib.ixpert.ops.wuwagent.model.OllamaChatResponse
import net.ib.ixpert.ops.wuwagent.model.OllamaMessage
import net.ib.ixpert.ops.wuwagent.service.metagraph.consumer.discovery.AdaptiveFileDiscovery
import net.ib.ixpert.ops.wuwagent.service.metagraph.consumer.discovery.DiscoveryResult
import net.ib.ixpert.ops.wuwagent.service.metagraph.consumer.discovery.MockSeedSelector
import net.ib.ixpert.ops.wuwagent.service.metagraph.consumer.discovery.SeedSelectionResult
import net.ib.ixpert.ops.wuwagent.service.metagraph.consumer.discovery.ChangeIntent
import net.ib.ixpert.ops.wuwagent.service.metagraph.model.ProjectGraph
import net.ib.ixpert.ops.wuwagent.service.metagraph.trimmer.ContextTrimmer
import org.junit.Test
import java.io.File

class ManualSimulationTest {
    
    private val artifactDir = "C:\\Users\\dffrp\\.gemini\\antigravity\\brain\\1cf1c9f8-1e55-4577-826a-dabb138299c6"

    @Test
    fun testManualSimulationReport() {
        val graphFile = File("C:\\Workspace\\member-market\\.meta\\project-graph.json")
        if (!graphFile.exists()) return
        
        val gson = GsonBuilder().disableHtmlEscaping().create()
        val graph = gson.fromJson(graphFile.readText(Charsets.UTF_8), ProjectGraph::class.java)

        val mockLlmClient = object : LLMClient {
            override fun chat(systemPrompt: String, userCode: String, maxTokens: Int?, onChunk: ((String) -> Unit)?): OllamaChatResponse? {
                return OllamaChatResponse(model = "mock", createdAt = "", message = OllamaMessage("assistant", "{}"), done = true)
            }
            override fun fetchModels(baseUrl: String, apiKey: String): List<String>? = listOf("mock")
        }

        val projectRoot = File("C:\\Workspace\\member-market")
        val report = StringBuilder()
        report.appendLine("# [Simulation Report (Graph Traversal)]")
        report.appendLine("This report shows the LLM input generated by the new Graph Traversal discovery pipeline.\n")

        val fixtures = mapOf(
            "TC-01" to SeedSelectionResult(listOf("Product", "ProductController"), ChangeIntent.MODIFY, listOf("ENTITY", "PRESENTATION"), true, "Mock TC-01"),
            "TC-02" to SeedSelectionResult(listOf("Member", "MemberController"), ChangeIntent.MODIFY, listOf("ENTITY", "PRESENTATION"), true, "Mock TC-02"),
            "TC-03" to SeedSelectionResult(listOf("ProductService", "ProductRepository"), ChangeIntent.MODIFY, listOf("SERVICE", "REPOSITORY"), false, "Mock TC-03"),
            "TC-04" to SeedSelectionResult(listOf("Product"), ChangeIntent.MODIFY, listOf("PRESENTATION"), true, "Mock TC-04"),
            "TC-05" to SeedSelectionResult(listOf("ProductStatus", "Product"), ChangeIntent.MODIFY, listOf("ENTITY", "PRESENTATION"), true, "Mock TC-05"),
            "TC-06" to SeedSelectionResult(listOf("Member", "MemberRepository", "MemberStatus"), ChangeIntent.CREATE, listOf("ENTITY", "REPOSITORY", "SERVICE"), false, "Mock TC-06"),
            "TC-07" to SeedSelectionResult(listOf("ChatMessage", "ChatRoom"), ChangeIntent.MODIFY, listOf("ENTITY", "SERVICE"), true, "Mock TC-07"),
            "TC-08" to SeedSelectionResult(listOf("ChatRoom", "ChatMessage"), ChangeIntent.MODIFY, listOf("ENTITY", "SERVICE"), true, "Mock TC-08"),
            "TC-09" to SeedSelectionResult(listOf("GlobalExceptionHandler", "ErrorCode"), ChangeIntent.MODIFY, listOf("CONFIG", "PRESENTATION"), false, "Mock TC-09"),
            "TC-10" to SeedSelectionResult(listOf("ProductRepository", "Product"), ChangeIntent.MODIFY, listOf("REPOSITORY"), false, "Mock TC-10")
        )
        val mockSeedSelector = MockSeedSelector(fixtures)

        val targetTcs = (1..10).map { "TC-%02d".format(it) }

        for (tcId in targetTcs) {
            val tc = TestCaseDefinitions.cases.find { it.srId == tcId } ?: continue
            
            report.appendLine("## Scenario: ${tc.srId} - ${tc.input.title}")
            report.appendLine("> **Requirement**: ${tc.input.description}\n")

            val discoveryResult = AdaptiveFileDiscovery.filter(
                primaryReq = "[${tc.srId}] " + tc.input.title,
                secondaryReq = tc.input.description,
                graph = graph,
                client = mockLlmClient,
                project = null,
                seedSelector = mockSeedSelector
            )

            val fileContents = mutableMapOf<String, String>()
            for (scoredFile in discoveryResult.relevantFiles) {
                val path = scoredFile.path
                val file = File(projectRoot, path)
                if (file.exists()) {
                    fileContents[path] = file.readText(Charsets.UTF_8)
                }
            }

            val trimmedFiles = mutableMapOf<String, String>()
            for (entry in fileContents) {
                val path = entry.key
                val content = entry.value
                val isSeed = discoveryResult.relevantFiles.find { it.path == path }?.hopDistance == 0
                val trimmed = ContextTrimmer.trimFile(path, content, isSeed)
                trimmedFiles[path] = trimmed
            }

            report.appendLine("### [Stage 1] Discovery Trace")
            report.appendLine("- **Seed Classes**: ${discoveryResult.metadata.seedClasses.joinToString()}")
            report.appendLine("- **Total Candidates**: ${discoveryResult.metadata.totalCandidates}")
            report.appendLine("- **Filtered To**: ${discoveryResult.metadata.filteredTo}\n")

            report.appendLine("#### Final List & Scores")
            discoveryResult.relevantFiles.forEach { sf ->
                report.appendLine("- `${sf.path}` (Score: ${sf.score}, Hop: ${sf.hopDistance}, Via: ${sf.discoveryReason})")
            }
            report.appendLine()

            report.appendLine("### [Stage 2] Context Trimming")
            if (trimmedFiles.isEmpty()) {
                report.appendLine("- No files.")
            }
            trimmedFiles.forEach { (path, trimmed) ->
                val originalLength = fileContents[path]?.length ?: 0
                val trimmedLength = trimmed.length
                val ratio = if (originalLength > 0) ((originalLength - trimmedLength).toDouble() / originalLength * 100).toInt() else 0
                report.appendLine("- `$path` : ${originalLength}B -> **${trimmedLength}B** (${ratio}% token saving)")
            }
            report.appendLine()

            report.appendLine("### [Stage 4] Prompt Injections")
            
            if (discoveryResult.suggestedNewFiles.isNotEmpty()) {
                report.appendLine("#### New File Proposals")
                discoveryResult.suggestedNewFiles.forEachIndexed { index, proposal ->
                    report.appendLine("**${index + 1}. ${proposal.suggestedPath.substringAfterLast('/')}**")
                    report.appendLine("- Path: `${proposal.suggestedPath}`")
                    report.appendLine("- Reason: ${proposal.reason}")
                    report.appendLine("- Reference: ${proposal.referencePattern}\n")
                }
            }

            report.appendLine("#### Modified Files (Samples)")
            var count = 0
            for (entry in trimmedFiles) {
                if (count >= 2) break
                val path = entry.key
                val content = entry.value
                report.appendLine("##### `$path`")
                val ext = path.substringAfterLast('.', "txt")
                report.appendLine("```$ext")
                report.appendLine(content)
                report.appendLine("```")
                report.appendLine()
                count++
            }
            report.appendLine("---\n")
        }

        File(artifactDir, "simulation_report.md").writeText(report.toString(), Charsets.UTF_8)
    }
}
